version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/tdd_python

    steps:
      # obtain code from github
      - checkout
      # create virtualenv and install dependencies
      - run:
        name: install dependencies
        command: |
          python3 -m venv virtualenv
          . venv/bin/activate
          pip install -r requirements.txt
      - run:
        name: run test
        command: |
          . venv/bin/activate
          python3 manage.py test accounts lists
          python3 manage.py test functional_tests
