version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@1.4.1
  node: circleci/node@5.1.0
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build1:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/tdd_python

    steps:
      # obtain code from github
      - checkout
      # install browser tools for firefox and chrome
      - browser-tools/install-firefox
      #- browser-tools/install-chrome
      #- browser-tools/install-chromedriver
      # install node
      # - node/install:
      #    node-version: '18.12.1'
      # create virtualenv and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv virtualenv
            . virtualenv/bin/activate
            pip install -r requirements.txt
            pip install -r test-requirements.txt
      - run:
          name: run tests
          command: |
            . virtualenv/bin/activate
            python3 manage.py test accounts lists
            python3 manage.py test functional_tests
          #  npm install node-qunit-puppeteer
          #  node_modules/node-qunit-puppeteer/cli.js lists/static/tests/tests.html

  build2:
    docker:
      - image: cimg/node:19.6.0

    working_directory: ~/tdd_python

    steps:
      - checkout
      #- run:
      #    name: Install Headless Chrome dependencies
      #    command: |
      #      sudo apt-get install libXtst6
      - run:
          name: Install puppeteer with chronium
          command: |
            npm i node-qunit-puppeteer
      - run:
          name: Javascript tests
          command: |
            node_modules/node-qunit-puppeteer/cli.js lists/static/tests/tests.html

workflows:
  version: '2.1'
  build_and_test:
    jobs:
      #- build1
      - build2
      #    requires:
      #      - build1
